### ISSUE TITLE
The new format of the ivory coast telephone number is not supported

### ISSUE THREAD

**Issue by chaabenMohamed** [jackocnr/intl-tel-input#1189]
Ivory coast changed its telephone number format on 31 January 2021, from 8 to 10 digits.
https://news.abidjan.net/h/677162.html

### Steps to reproduce
1.  try to whrite a phone number for ivory coast with 10 digits

### Expected behaviour
The phone number should be valid

### Actual behaviour
The phone number is not accepted as valid phone number for Ivory coast

**Comment by jackocnr** [comment]
We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting, validation and generating placeholder numbers - if your issue relates to one of these things, please check [their test site](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) first and if you see the problem there please file an issue with them instead.

If it's working correctly in libphonenumber, the next step is to check that we're using [the latest version](https://github.com/google/libphonenumber/releases) of libphonenumber in the plugin - check the version history [here](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js). If we need to upgrade, it only takes 5 minutes to do this yourself and submit a Pull Request - instructions here: [Updating to a new version of libphonenumber](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#updating-to-a-new-version-of-libphonenumber).

**Comment by jackocnr** [comment]
Note: we just released a new version with an upgraded libphonenumber - please can you see if that fixes your issue?

**Comment by chaabenMohamed** [comment]
The issue doesn't exist in libphonenumber, their demo page: https://libphonenumber.appspot.com/phonenumberparser?number=0748436784&country=CI
But the bug still exists in intl-tel-input in the last release!

**Comment by jackocnr** [comment]
Hmm I see libphonenumber have actually just released a new version v8.12.18 (5 hours ago!), which does include updates to Ivory Coast meta data - if we update to that it should solve the issue.

**Comment by jonathan42** [comment]
#1213 ?

**Comment by jackocnr** [comment]
I've just published a new version (v17.0.13) using a newer version of libphonenumber, which should have fixed the issue. Feel free to post here if you're still seeing the issue tho.
