### ISSUE TITLE
Invalid phone number issue for Ireland

### ISSUE THREAD

**Issue by syedhamidalishah404** [jackocnr/intl-tel-input#1705]
I am experiencing an issue, When I select Ireland and enter Ireland's phone number it is bieng marked as invalid, Could you please look into this?

Thanks.

**Comment by jackocnr** [comment]
Can you give an example of a valid Irish number that is being marked as invalid?

**Comment by syedhamidalishah404** [comment]
Hi jack,

Thanks for your response.

For example, I am using this number: 085 209 6303, which is a valid Irish mobile number but it's being marked as invalid.

I am also including the relevant code for you to look over.
  
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/countries.js') ?>"></script>
    <script src="<?php echo $this->getSkinUrl('phone-validation/js/intlTelInputWithUtils.js'); ?>"></script>
    <script type="text/javascript">
        var contactForm = new VarienForm('contactForm', true);
        let phoneNumber;
        var input = document.getElementById("telephone"),
            cellInput = window.intlTelInput(input, {
                geoIpLookup: function (callback) {
                    var countryCode = document.getElementById('country').value;
                    callback(countryCode);
                },
                initialCountry: "<?php echo strtolower($store); ?>",
                i18n: allCountries,
                nationalMode: true,
                strictMode: true,
                validationNumberType: "FIXED_LINE_OR_MOBILE",
                autoPlaceholder: 'aggressive',
                placeholderNumberType: "MOBILE",
                useFullscreenPopup: false,
                hiddenInput: () => ({ phone: "telephone"}),
            });

        cellInput.promise.then(function() {
            cellInputValidation(input.placeholder);
        });

        input.addEventListener('countrychange', function(e) {
            cellInputValidation(input.placeholder);
        });

        function cellInputValidation(inputPlaceholder){
            if (cellInput.isValidNumber()) {
                console.log('yes isValidNumber');
            } else {
                console.log('not isValidNumber');
            }
        }
        input.addEventListener('blur', function (e) {
            if (typeof window.intlTelInput !== 'undefined' && typeof cellInput !== 'undefined') {
                phoneNumber = cellInput.getNumber(intlTelInput.numberFormat);
            }
            cellInputValidation(input.placeholder)
        });
        input.addEventListener('input', function (e) {
            cellInputValidation(input.placeholder)
        });
    </script>
    
Thanks again for your help.

Best regards,
Syed Hamid

**Comment by syedhamidalishah404** [comment]
I have also tried with the latest version of the plugin, but the issue persists. Any further suggestions would be greatly appreciated.

**Comment by jackocnr** [comment]
Did you also update utils.js to the latest version?

**Comment by syedhamidalishah404** [comment]
Yes, I have updated utils.js to the latest version.

**Comment by syedhamidalishah404** [comment]
But the issue persists

**Comment by jackocnr** [comment]
If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/wvQmzJO) with the plugin up and running - feel free to fork this if it helps.

**Comment by syedhamidalishah404** [comment]
Hi Jack,

Please use this link `[link](https://codepen.io/Syed-Hamid-Ali-Shah/pen/VwJeXOv)`. and open the developer tools, then navigate to the console tab, Then, enter the Irish number and select Ireland from the country list. You will see an invalid message in the console.

**Comment by syedhamidalishah404** [comment]
Or you use this:
https://codepen.io/Syed-Hamid-Ali-Shah/pen/OJeMZbO

**Comment by jackocnr** [comment]
Thanks for that. The problem is that you've changed `validationNumberType` from the default of `"MOBILE"` to `"FIXED_LINE_OR_MOBILE"`. Can I ask why you've done this?

**Comment by syedhamidalishah404** [comment]
@jackocnr 
because we want both types of the number to be validated.

**Comment by jackocnr** [comment]
Yes I assumed as much, but just wanted to check. Confusingly, that's not how "FIXED_LINE_OR_MOBILE" works. It sounds like it means it's either a FIXED_LINE number or a MOBILE number, but actually it's its own third category which is separate from the others (e.g. for American numbers, which could be either type of number). It should really be called "FIXED_LINE_SLASH_MOBILE" or something like that. Anyway, I think this is so confusing that I will add a workaround for it in the code. I will release something for this soon, so in your case it will return valid. I'll let you know when it's done.

**Comment by syedhamidalishah404** [comment]
Thank you, @jackocnr. Looking forward to the update

Best regards,
[@hamidkodez](https://github.com/hamidkodez)

**Comment by jackocnr** [comment]
This should now be working in v23.6.0

**Comment by syedhamidalishah404** [comment]
Hi @jackocnr, I just checked, and it's still not validating. I also commented out the line 'validationNumberType: "FIXED_LINE_OR_MOBILE",' and tested both types of Irish numbers, mobile and landline.

**Comment by jackocnr** [comment]
>  I just checked, and it's still not validating

It's working for me: https://codepen.io/jackocnr/pen/yLdJNJd?editors=0010

Are you sure you updated your utils.js?

Anyway, If you can fork that codepen and reproduce your issue, I'd be happy to take a look.

> I also commented out the line 'validationNumberType: "FIXED_LINE_OR_MOBILE"'

Note that when you don't specify this, the default value is "MOBILE", so only mobile numbers will validate as true.

**Comment by syedhamidalishah404** [comment]
Hi @jackocnr,

Thanks for your help! It's working now. I appreciate your help and quick response.

Best regards.
@hamidkodez
