### ISSUE TITLE
Incorrect format when the length of country code is 4

### ISSUE THREAD

**Issue by JasonMrX** [jackocnr/intl-tel-input#388]
This issue happens only when separateDialCode option is on

### Steps to reproduce
1.  select American Samoa +1684 (code length is 4)
1.  input 1234567
2.  save after internationalization => +16841234567
3.  formatOnInit

### Expected behaviour
Should be formatted to 123-4567

### Actual behaviour
Formatted to 4-123-4567
Place holder format is also problematic

### Possible Reason
After intlTelInputUtils.formatNumber method, an additional space is inserted after +1 when country code length is 4. This makes the _beforeSetNumber method fail (incorrect prefix length)

### Initialisation options
formatOnInit: true,
separateDialCode: true,
utilsScript: "path/to/utils.js"

### Additional Comments
I want the country codes to be displayed in my app, to prevent user from inserting additional country code manually, so I always turn the separateDialCode on. I think it's a nice feature.

**Comment by JasonMrX** [comment]
### Follow up
This issue happen after last bug fix (v8.4.6)

**Comment by jackocnr** [comment]
It seems to be working for me: http://codepen.io/jackocnr/pen/yehvE

Are you sure you're using the latest version? If so, are you able to repro the issue in a codepen?

**Comment by JasonMrX** [comment]
I tried but I can't repro in a codepen either. But it's still in my app.

I am using rails 4 and I've update the my jquery to 2.1.3 which is the same as the one used in codepen.

Here is the input html code I had directly after I render the page:
`<input class="form-control required" type="tel" value="+16841234567" name="personal_information[phone]" id="personal_information_phone" autocomplete="off" placeholder="4-733-1234" data-original-title="" title="">`

And here is the screenshot of my input:
![image](https://cloud.githubusercontent.com/assets/13440746/13624628/ec0902c2-e57d-11e5-9268-114be1fe81eb.png)

I've double checked that I am using the latest version. I even did a file comparison with the file used in the codepen and they are identical. But the outcome is different. So weird..

Any suggestions would be appreciated.

**Comment by JasonMrX** [comment]
In the codepen you provided, If you empty the input val manually, you will see that the place holder is actually incorrect, which is exactly the bug that I am getting.

**Comment by jackocnr** [comment]
You're right. Thanks again. Fixed in v8.4.7.

**Comment by JasonMrX** [comment]
Hi again. I think the bug persists in the minified version. Would you mind check it again?

**Comment by JasonMrX** [comment]
Sorry. My mistake. The newest release is good.
