### ISSUE TITLE
International number with Calling Code that Starts with a 1 formats as US

### ISSUE THREAD

**Issue by toddca** [jackocnr/intl-tel-input#475]
### Steps to reproduce
1.  Select American Somoa (+1684)
2.  Type a number such as '9785585898'
3.  Use intlTelInput("getNumber") and number returned is a US based number +19785585898 vs the correct number which should be +16849785585898 - note this is an issue for every calling code that begins with a 1
### Expected behaviour

the correct number which should be +16849785585898
### Actual behaviour

number returned is a US based number +19785585898 
### Initialisation options

using utilsScript, preferredCountries is default, using just .intlTelInput(); to init

**Comment by jackocnr** [comment]
Thanks for reporting this. We use [libphonenumber](https://github.com/googlei18n/libphonenumber) for formatting/validation (e.g. when you call `getNumber`), and it seems that it expects the "684" prefix to be included in the number. I think the solution for us would be to add some code in the `_getFullNumber` method to check that if the currently selected country has a dial code then to check if that is included in the number, and if not then add it.

Unfortunately I don't have time to implement this myself right now, but I would be open to a pull request.

**Comment by tmorehouse** [comment]
Similarly, if a north american toll free number is typed in when you have Canada selected, (say 800 555 1212), the flag automatically changes to the US flag, although the number isn't necessarily tied to any particular north american country.

**Comment by jackocnr** [comment]
@tmorehouse thanks for reporting that - it's actually a separate issue (the op's issue is with the `getNumber` method). Please could you open a separate issue for it?

**Comment by tmorehouse** [comment]
@jackocnr opened as #503

**Comment by jackocnr** [comment]
Fixed in v9.2.5.

**Comment by toddca** [comment]
This is still not fixed. Try adding a valid American Somoa by typing '2581344' after choosing the prefix and you will see a validation error.

**Comment by jackocnr** [comment]
If you're talking about [the validation example on the demo site](http://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html), I just hadn't updated it to use the latest version, but I have now, and it's working for the example you provide.
