### ISSUE TITLE
Showing Russian flag for Kazakhstan number

### ISSUE THREAD

**Issue by jyotsnagaddam** [jackocnr/intl-tel-input#912]
### Steps to reproduce
1. Please take any Kazakhstan number online
2.  Go to the demo page https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/is-valid-number.html
3.  And enter the number

### Expected behaviour
Should show Kazakhstan country flag

### Actual behaviour
But showing Russian Flag

### Initialisation options
List any options you're using e.g. utilsScript or preferredCountries

**Comment by jyotsnagaddam** [comment]
Note: Both Russia and Kazakhstan share same international dial code (+7)

Based on the below specification and data:
 // So each country array has the following information:
    // [
    //    Country name,
    //    iso2 code,
    //    International dial code,
    //    Order (if >1 country with same dial code),
    //    Area codes (if >1 country with same dial code)
    // ]


[
    "Kazakhstan (Казахстан)",
    "kz",
    "7",
    1
  ],

**As area codes are missing above, it seems it showing the Russian flag based on the priority set**

**Comment by jackocnr** [comment]
Well spotted. So currently we only support "area codes" for countries that share the international dial code of +1, but actually we also need to support them for +7 (shared by Russia and Kazakhstan), as well as the following others: +39, +44, +47, +61, +212, +262, +358, +590, +599, which are all used by more than one country/territory.

The first step is to collect the list of area codes for each of these countries - is that something you could do, and just post them here for reference?

**Comment by jyotsnagaddam** [comment]
I have attached the "area codes" for the countries that share the international dial code.

Note:
- Some countries share common area codes and cannot be separated. (Ex: Guadeloupe, Saint Barthelemy, Saint Martin)
- Some Islands are uninhabited or with temporary inhabitants.
- Vatican City is with in the Rome and shares same area code (06) but the numbers usually starts with 698.

References: 
https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml

Cross References:
- https://www.itu.int/oth/T0202.aspx?lang=en&parent=T0202
- https://en.wikipedia.org/wiki/List_of_country_calling_codes
- https://www.howtocallabroad.com/

Better have it someone review the attachment.
[Area Codes.xlsx](https://github.com/jackocnr/intl-tel-input/files/3270693/Area.Codes.xlsx)

**Comment by jackocnr** [comment]
This is great thanks!

In addition to the ones you have found, I think we can define the area codes for a few more countries as well - see the "leadingDigits" section for the following countries (confirmed by searching Google Maps for hotels in that country, and then copying the phone number for a hotel into the [libphonenumber test page](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) and submitting, and seeing it identify the correct country): [Western Sahara](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L8602), [Aland Islands](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L2581), [Vatican City](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L26871) and [Svalbard](https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L23859).

The next step is to add these area codes to src/js/data.js, following [the existing formatting](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L9) - is that something you could tackle?

**Comment by jyotsnagaddam** [comment]
Attached is the updated document. For 'Aland Islands' and 'Svalbard' the area codes are already updated in previous document. In this doc I have added for 'Western Sahara' and 'Vatican City' as mentioned by you. Additionally I have removed the area codes that are mentioned exclusively for 'Kazakhstan' and added leading digits there as well. Please review.

[Area Codes.xlsx](https://github.com/jackocnr/intl-tel-input/files/3273435/Area.Codes.xlsx)

**Comment by jackocnr** [comment]
Looks good to me, thanks.

Note that you have a few countries in there that we don't support, namely: French Southern and Antarctic Lands, Tristan da Cunha, Nagorno-Karabakh, Bouvet Island, South Georgia and the South Sandwich Islands, Pitcarin Islands, Australian Antarctic Territory, Heard Island and McDonald Islands, Northern Cyprus. We have clear criteria for countries for them to be included: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L3

But yeah, aside from those countries, I'd say this data is ready to go into data.js. Thanks.

**Comment by jackocnr** [comment]
Fix released in v15.1.1.

**Comment by jyotsnagaddam** [comment]
@jackocnr, I think this issue is not fixed completely. Please find the attached media file. 
Steps to reproduce the issue:
1. Type +7, we will see Russian flag
2. Type +7343, we will see Russian flag as 343 area code belongs to Russia
3. Type +733, we will see Kazakhstan as '33' are leading digits for that
4. **Type +7343 again, you will still see Kazakhstan flag instead of Russian flag.**

This is because [while updating the flag](https://github.com/jackocnr/intl-tel-input/blob/2adfeec364566251d26e71dcd0b0e049923a6a11/src/js/intlTelInput.js#L850) the const  'isNanpAreaCode' is false for rest of the countries who share the same dial code. Instead we can check for countryCodes.length > 1, this will work with all countries that share the same dial code. Hence the if condition should look like below:

`if (!isRegionlessNanpNumber && (!alreadySelected || countryCodes.length > 1)) {`

[Kazakhstan flag is not changing back to Russian.zip](https://github.com/jackocnr/intl-tel-input/files/3312395/Kazakhstan.flag.is.not.changing.back.to.Russian.zip)

**Comment by jackocnr** [comment]
Confirmed. Thanks for reporting and suggesting a fix. I will review over the weekend.

**Comment by jackocnr** [comment]
Turned out to be a bit more complicated, but I think I've fixed it now, and [pushed that change to master](https://github.com/jackocnr/intl-tel-input/commit/5b1328e0062edb77a8ca4247df68034d5849eef2). It will be included in the next release. Thanks again.

**Comment by jyotsnagaddam** [comment]
> Turned out to be a bit more complicated, but I think I've fixed it now, and [pushed that change to master](https://github.com/jackocnr/intl-tel-input/commit/5b1328e0062edb77a8ca4247df68034d5849eef2). It will be included in the next release. Thanks again.

@jackocnr, Thanks for fixing this!
Yes, I see you made lot of changes. Can I know tentative date for next release?

**Comment by jackocnr** [comment]
Released in v16.0.0.

**Comment by jyotsnagaddam** [comment]
> Released in v16.0.0.

Great, Thanks !!

**Comment by pushljupche** [comment]
@jackocnr looks like this issue has returned. I'm using v17.0.0 and if I select a country that has +1 but it's not US, when I start typing the country flag will change to US. The issue can be replicated on the demo site:
http://intl-tel-input.com/
